import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";


const cairo = Cairo({
 variable:"--font-cairo",
 subsets:["arabic"],
 weight: ["400", "500", "600", "700"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "سَنَد - sanad",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={` ${cairo.variable} antialiased bg-background`}
      >
       <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
